// easier way?
declare module '@enact/moonstone';
declare module '@enact/moonstone/Button';
declare module '@enact/moonstone/Input';
declare module '@enact/moonstone/Item';
declare module '@enact/moonstone/MoonstoneDecorator';
declare module '@enact/moonstone/Panels';
declare module '@enact/ui/resolution';
declare module '@enact/ui/VirtualList';
declare module '@enact/ui/resolution';